# ================================================
# FILE: core/events.py
# ================================================

class CmdEvents:
    START_LOCAL_TURN = "CMD_START_LOCAL_TURN"
    TOGGLE_PAUSE = "CMD_TOGGLE_PAUSE"
    END_TURN_SUCCESS = "CMD_END_TURN_SUCCESS"
    END_TURN_ELIMINATED = "CMD_END_TURN_ELIMINATED"
    LAUNCH_DAW = "CMD_LAUNCH_DAW"
    WAIT_DAW_INTERACTION = "CMD_WAIT_DAW_INTERACTION"
    WAIT_RESUME_CLICK = "CMD_WAIT_RESUME_CLICK"
    WAIT_DAW_EXIT = "CMD_WAIT_DAW_EXIT"
    FORCE_AUTO_SAVE = "CMD_FORCE_AUTO_SAVE"
    STOP_DAW_MONITOR = "CMD_STOP_DAW_MONITOR"
    PREPARE_WORKSPACE = "CMD_PREPARE_WORKSPACE"
    VERIFY_WORKSPACE = "CMD_VERIFY_WORKSPACE"
    STOP_HANDSHAKE_CHECK = "CMD_STOP_HANDSHAKE_CHECK"
    SEND_SOCIAL_MESSAGE = "CMD_SEND_SOCIAL_MESSAGE"
    BROADCAST_PRESENCE = "CMD_BROADCAST_PRESENCE"
    WAIT_FOR_LOCK = "CMD_WAIT_FOR_LOCK"
    WATCH_DOWNLOAD = "CMD_WATCH_DOWNLOAD"
    STOP_SYNC_MONITOR = "CMD_STOP_SYNC_MONITOR"
    CHECK_FOR_UPDATES = "CMD_CHECK_FOR_UPDATES"
    START_UPDATE = "CMD_START_UPDATE"
    RETURN_TO_LOBBY = "CMD_RETURN_TO_LOBBY"
    ANALYZE_MATCH = "CMD_ANALYZE_MATCH"


class StateEvents:
    MATCH_STARTED = "STATE_MATCH_STARTED"
    TURN_START = "STATE_TURN_START"
    PAUSED = "STATE_PAUSED"
    RESUMED = "STATE_RESUMED"
    TURN_END = "STATE_TURN_END"
    ELIMINATED = "STATE_ELIMINATED"
    FINISHED = "STATE_FINISHED"
    GAME_OVER = "STATE_GAME_OVER"
    TIMER_TICK = "STATE_TIMER_TICK"
    TIME_UP = "STATE_TIME_UP"
    ANALYSIS_COMPLETE = "STATE_ANALYSIS_COMPLETE"


class NetEvents:
    TURN_START = "NET_TURN_START"
    PREPARE_SYNC = "NET_PREPARE_SYNC"
    TURN_END = "NET_TURN_END"
    PAUSE = "NET_PAUSE"
    RESUME = "NET_RESUME"
    ELIMINATED = "NET_ELIMINATED"
    FINISHED = "NET_FINISHED"
    CLIENT_LEAVE = "NET_CLIENT_LEAVE"
    CONNECTED = "NET_CONNECTED"
    CLIENT_JOIN = "NET_CLIENT_JOIN"
    NAME_TAKEN = "NET_NAME_TAKEN"
    SYNC_STATE = "NET_SYNC_STATE"
    FOLDER_VERIFIED = "NET_FOLDER_VERIFIED"
    LOBBY_CLOSED = "NET_LOBBY_CLOSED"
    START_MATCH = "NET_START_MATCH"


class SysEvents:
    TICK = "SYS_TICK"
    FL_WARNING_SHOW = "SYS_FL_WARNING_SHOW"
    FL_WARNING_HIDE = "SYS_FL_WARNING_HIDE"
    FL_MANUAL_START_BLOCKED = "SYS_FL_MANUAL_START_BLOCKED"
    FILE_CORRUPTED = "SYS_FILE_CORRUPTED"
    WORKSPACE_READY = "SYS_WORKSPACE_READY"
    HANDSHAKE_SUCCESS = "SYS_HANDSHAKE_SUCCESS"
    HANDSHAKE_TIMEOUT = "SYS_HANDSHAKE_TIMEOUT"
    HANDSHAKE_ERROR = "SYS_HANDSHAKE_ERROR"
    DAW_NOT_FOUND = "SYS_DAW_NOT_FOUND"

    # NEU: Events für Rclone & Cloud Sync (Fail Fast)
    CLOUD_AUTH_SUCCESS = "SYS_CLOUD_AUTH_SUCCESS"
    CLOUD_AUTH_FAILED = "SYS_CLOUD_AUTH_FAILED"
    SYNC_ERROR = "SYS_SYNC_ERROR"
    SYNC_SUCCESS = "SYS_SYNC_SUCCESS"


class UIEvents:
    STATUS_UPDATE = "UI_STATUS_UPDATE"
    LOBBY_REFRESH = "UI_LOBBY_REFRESH"
    LOBBY_SYNCED = "UI_LOBBY_SYNCED"
    LOBBY_ERROR_NAME_TAKEN = "UI_LOBBY_ERROR_NAME_TAKEN"
    LOBBY_ERROR_HANDSHAKE = "UI_LOBBY_ERROR_HANDSHAKE"
    LOBBY_HOST_CLOSED = "UI_LOBBY_HOST_CLOSED"
    UX_START_TURN = "UX_START_TURN"
    UX_END_TURN = "UX_END_TURN"
    UX_SHOW_WARNING = "UX_SHOW_WARNING"
    LANGUAGE_CHANGED = "LANGUAGE_CHANGED"
    SETTINGS_UPDATED = "SETTINGS_UPDATED"
    OBS_UPDATE = "OBS_UPDATE"


class SocialEvents:
    FRIENDS_UPDATED = "SOCIAL_FRIENDS_UPDATED"
    FRIEND_STATUS = "SOCIAL_FRIEND_STATUS"
    FRIEND_REQUEST_RECEIVED = "SOCIAL_FRIEND_REQUEST_RECEIVED"
    INVITE_RECEIVED = "SOCIAL_INVITE_RECEIVED"


class UpdaterEvents:
    AVAILABLE = "UPDATER_AVAILABLE"
    PROGRESS = "UPDATER_PROGRESS"
    ERROR = "UPDATER_ERROR"